name: Fuzz Nightly

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  fuzz-nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fuzz_target: [token-swap-instructions]
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          source ci/rust-version.sh
          echo "RUST_STABLE=$rust_stable" >> $GITHUB_ENV
          source ci/solana-version.sh
          echo "SOLANA_VERSION=$solana_version" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
          override: true
          profile: minimal

      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-fuzz-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-fuzz-

      - name: Cache fuzzing tools
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/cargo-hfuzz
            ~/.cargo/bin/cargo-honggfuzz
          key: cargo-fuzz-bins-${{ runner.os }}

      - name: Cache Solana dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/solana
          key: solana-${{ env.SOLANA_VERSION }}
          restore-keys: |
            solana-

      - name: Install build and program dependencies
        run: |
          ./ci/install-build-deps.sh
          ./ci/install-program-deps.sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Run fuzz target
        run: ./ci/fuzz.sh ${{ matrix.fuzz_target }} 18000 # 5 hours, jobs max out at 6
